CREATE DATABASE QuanLyTiemChung
GO
USE QuanLyTiemChung
GO 

CREATE TABLE KHACHHANG(
	MAKH char(7) PRIMARY KEY,
	HOTEN nvarchar(30) NOT NULL,
	NGSINH DATE NOT NULL,
	GIOITINH char(3) NOT NULL,
	DIACHI nvarchar(40) NOT NULL,
	SDT char(10) NOT NULL,
	MATHE char(30),
	MANGH char(7)
)

CREATE TABLE NGUOIGIAMHO(
	MANGH char(7) PRIMARY KEY,
	HOTEN nvarchar(30) NOT NULL,
	SDT char(10) NOT NULL,
	MQH nvarchar(30) NOT NULL
)

CREATE TABLE PHIEUTIEMVACXIN(
	MAPT char(7) PRIMARY KEY,
	MAKH char(7) NOT NULL,
	MANV char(7) NOT NULL,
	MAHD char(7) NOT NULL,
	NGLAP DATE NOT NULL
)

CREATE TABLE CT_PHIEUTIEM(
	MAPT char(7),
	MAVX char(7),
	DONGIA int NOT NULL,
	NGTIEM DATE NOT NULL,

	PRIMARY KEY(MAPT,MAVX)
)

CREATE TABLE VACXIN(
	MAVX char(7) PRIMARY KEY,
	TENVX nvarchar(20) NOT NULL,
	GIA int NOT NULL,
	THONGTIN nvarchar(20) NOT NULL,
	SLTON int NOT NULL
)

CREATE TABLE GOIVACXIN(
	MAGOI char(7) PRIMARY KEY,
	TENGOI nvarchar(20) NOT NULL,
	GIA int NOT NULL,
	THONGTIN nvarchar(20) NOT NULL,
	SLTON int NOT NULL
)

CREATE TABLE CT_GOITIEM(
	MAGOI char(7),
	MAVX char(7),

	PRIMARY KEY(MAGOI,MAVX)
)

CREATE TABLE CT_DONMUA(
	MADDM char(7),
	MAVX char(7),
	SOLUONG int,

	PRIMARY KEY(MADDM,MAVX)
)

CREATE TABLE DONMUA(
	MADDM char(7) PRIMARY KEY,
	MAKH char(7),
	MANV char(7),
	MADDH char(7),
	NGLAP date,
	DADUYET int
)

CREATE TABLE DONDATHANG(
	MADDH char(7),
	NGLAP int,

	PRIMARY KEY(MADDH)
)

CREATE TABLE CT_DONDAT(
	MADDH char(7),
	MANCC char(7),

	PRIMARY KEY(MADDH,MANCC)
)

CREATE TABLE NHACUNGCAP(
	MANCC char(7) PRIMARY KEY,
	TENNCC nvarchar(30) NOT NULL,
	SDT char(10) NOT NULL
)

CREATE TABLE HOADON(
	MAHD char(7) PRIMARY KEY,
	MANV char(7) NOT NULL,
	NGLAP date,
	HTTT varchar(10) NOT NULL,
)

CREATE TABLE DOTTHANHTOAN(
	STT char(7),
	MAHD char(7),
	TINHTRANG varchar(20) NOT NULL,
	THANHTIEN int NOT NULL,
	NGAYTT date,
	
	PRIMARY KEY(STT,MAHD)
)

CREATE TABLE NHANVIEN(
	MANV char(7) PRIMARY KEY,
	HOTEN nvarchar(30) NOT NULL,
	NGSINH DATE NOT NULL,
	GIOITINH char(3) NOT NULL,
	DIACHI nvarchar(40) NOT NULL,
	SDT char(10) NOT NULL,
	BANGCAP nvarchar(20) NOT NULL,
	EMAIL nvarchar(30) NOT NULL,
	LUONG int NOT NULL,
	MATT char(7),
	MALOAI char(7)
)

CREATE TABLE TRUNGTAM(
	MATT char(7) PRIMARY KEY,
	DIACHI nvarchar(40) NOT NULL
)

CREATE TABLE LOAINV(
	MALOAI char(7) PRIMARY KEY,
	TENLOAI nvarchar(40) NOT NULL
)

CREATE TABLE LICH(
	MALICH char(7) PRIMARY KEY,
	CA int NOT NULL,
	THU int NOT NULL,
	NGAYBATDAU date,
	DUYET INT
)

CREATE TABLE NV_LICH(
	MALICH char(7),
	MANV char(7),

	PRIMARY KEY(MALICH, MANV)
)
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KH_NGH FOREIGN KEY (MANGH) REFERENCES NGUOIGIAMHO(MANGH)

ALTER TABLE PHIEUTIEMVACXIN
ADD CONSTRAINT FK_KH_PT FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE PHIEUTIEMVACXIN
ADD CONSTRAINT FK_NV_PT FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE PHIEUTIEMVACXIN
ADD CONSTRAINT FK_HD_PT FOREIGN KEY (MAKH) REFERENCES HOADON(MAHD)

ALTER TABLE CT_GOITIEM
ADD CONSTRAINT FK_GOI_VX FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
ALTER TABLE CT_GOITIEM
ADD CONSTRAINT FK_VX_GOI FOREIGN KEY (MAGOI) REFERENCES GOIVACXIN(MAGOI)

ALTER TABLE CT_PHIEUTIEM
ADD CONSTRAINT FK_PT_VX FOREIGN KEY (MAPT) REFERENCES PHIEUTIEMVACXIN(MAPT)
ALTER TABLE CT_PHIEUTIEM
ADD CONSTRAINT FK_VX_PT1 FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
ALTER TABLE CT_PHIEUTIEM
ADD CONSTRAINT FK_VX_PT2 FOREIGN KEY (MAVX) REFERENCES GOIVACXIN(MAGOI)

ALTER TABLE CT_DONMUA
ADD CONSTRAINT FK_DM_VX FOREIGN KEY (MADDM) REFERENCES DONMUA(MADDM)
ALTER TABLE CT_DONMUA
ADD CONSTRAINT FK_VX_DM1 FOREIGN KEY (MAVX) REFERENCES VACXIN(MAVX)
ALTER TABLE CT_DONMUA
ADD CONSTRAINT FK_VX_DM2 FOREIGN KEY (MAVX) REFERENCES GOIVACXIN(MAGOI)

ALTER TABLE DONMUA
ADD CONSTRAINT FK_DM_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE DONMUA
ADD CONSTRAINT FK_DM_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE DONMUA
ADD CONSTRAINT FK_DM_DDH FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH)

ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_TT FOREIGN KEY (MATT) REFERENCES TRUNGTAM(MATT)
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAINV(MALOAI)

ALTER TABLE NV_LICH
ADD CONSTRAINT FK_NV_LICH1 FOREIGN KEY (MALICH) REFERENCES LICH(MALICH)
ALTER TABLE NV_LICH
ADD CONSTRAINT FK_NV_LICH2 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE HOADON
ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE DOTTHANHTOAN
ADD CONSTRAINT FK_HD_DOT FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CT_DONDAT
ADD CONSTRAINT FK_DDH_NCC FOREIGN KEY (MADDH) REFERENCES DONDATHANG(MADDH)
ALTER TABLE CT_DONDAT
ADD CONSTRAINT FK_NCC_DDH FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)

